service: entry
frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          # Restrict our IAM role permissions to
          # the specific table for the stage
          Resource:
            - "arn:aws:dynamodb:eu-central-1:552798860484:table/lambda"

functions:
  startScrapeFlow:
    handler: handler.handler
    maximumRetryAttempts: 0
    timeout: 900
    # provisionedConcurrency: 1 #leaving these in makes the schedule not trigger
    # reservedConcurrency: 1 #leaving these in makes the schedule not trigger
    events:
      - httpApi: '*'
      - schedule: rate(1 minute)
