service: scrape
frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          # Restrict our IAM role permissions to
          # the specific table for the stage
          Resource:
            - "arn:aws:dynamodb:eu-central-1:552798860484:table/lambda"

functions:
  scrape:
    handler: handler.handler
    events:
      - httpApi: '*'
